#include "sparse_csr_matrix_vector_multiplication_nospir_opencl120.h"

namespace ocl {
	static const ocl::VersionedBinary* opencl_versioned_binaries_sparse_csr_matrix_vector_multiplication[] = {
		&opencl_binary_sparse_csr_matrix_vector_multiplication_nospir_opencl120
	};
	static ProgramBinaries opencl_binaries_sparse_csr_matrix_vector_multiplication = ProgramBinaries(std::vector<const VersionedBinary *>(opencl_versioned_binaries_sparse_csr_matrix_vector_multiplication, opencl_versioned_binaries_sparse_csr_matrix_vector_multiplication + sizeof(opencl_versioned_binaries_sparse_csr_matrix_vector_multiplication) / sizeof(opencl_versioned_binaries_sparse_csr_matrix_vector_multiplication[0])), "sparse_csr_matrix_vector_multiplication");
}
