#include "matrix_05_multiply_cooperative_matrix_comp_spirv_vulkan.h"

namespace avk2 {
	static const avk2::VersionedBinary* vulkan_versioned_binaries_matrix_05_multiply_cooperative_matrix_comp[] = {
		&vulkan_binary_matrix_05_multiply_cooperative_matrix_comp_spirv,
	};
	static ProgramBinaries vulkan_binaries_matrix_05_multiply_cooperative_matrix_comp = ProgramBinaries(std::vector<const VersionedBinary *>(vulkan_versioned_binaries_matrix_05_multiply_cooperative_matrix_comp, vulkan_versioned_binaries_matrix_05_multiply_cooperative_matrix_comp + sizeof(vulkan_versioned_binaries_matrix_05_multiply_cooperative_matrix_comp) / sizeof(vulkan_versioned_binaries_matrix_05_multiply_cooperative_matrix_comp[0])), "matrix_05_multiply_cooperative_matrix_comp");
}
