#include "matrix_04_multiply_via_local_memory_comp_spirv_vulkan.h"

namespace avk2 {
	static const avk2::VersionedBinary* vulkan_versioned_binaries_matrix_04_multiply_via_local_memory_comp[] = {
		&vulkan_binary_matrix_04_multiply_via_local_memory_comp_spirv,
	};
	static ProgramBinaries vulkan_binaries_matrix_04_multiply_via_local_memory_comp = ProgramBinaries(std::vector<const VersionedBinary *>(vulkan_versioned_binaries_matrix_04_multiply_via_local_memory_comp, vulkan_versioned_binaries_matrix_04_multiply_via_local_memory_comp + sizeof(vulkan_versioned_binaries_matrix_04_multiply_via_local_memory_comp) / sizeof(vulkan_versioned_binaries_matrix_04_multiply_via_local_memory_comp[0])), "matrix_04_multiply_via_local_memory_comp");
}
